// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4mFz1jIAI3ThBoELtZ_laeHoDG1Fsw2A',
    appId: '1:1098205578075:web:c1e90530bbb0509d6bd07e',
    messagingSenderId: '1098205578075',
    projectId: 'harithakarma',
    authDomain: 'harithakarma.firebaseapp.com',
    storageBucket: 'harithakarma.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC2eNuKA4ibjMfV5J1fy8hsvlhkqvnQdc',
    appId: '1:1098205578075:android:38f3c965a7aae9fb6bd07e',
    messagingSenderId: '1098205578075',
    projectId: 'harithakarma',
    storageBucket: 'harithakarma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa0CDH8hP37phpxeJiMsd62AImLC20ifU',
    appId: '1:1098205578075:ios:60d23b4d0863e55f6bd07e',
    messagingSenderId: '1098205578075',
    projectId: 'harithakarma',
    storageBucket: 'harithakarma.appspot.com',
    iosClientId: '1098205578075-eqknb8egiqosnle0uf8fk46l1f9ci5sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.harithakarma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa0CDH8hP37phpxeJiMsd62AImLC20ifU',
    appId: '1:1098205578075:ios:60d23b4d0863e55f6bd07e',
    messagingSenderId: '1098205578075',
    projectId: 'harithakarma',
    storageBucket: 'harithakarma.appspot.com',
    iosClientId: '1098205578075-eqknb8egiqosnle0uf8fk46l1f9ci5sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.harithakarma',
  );
}
